export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"Kalyankari Collection","icon":"fa6-solid:house"} }],
  ["/wiki/Android.html", { loader: () => import(/* webpackChunkName: "wiki_Android.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Android.html.js"), meta: {"title":"Android","icon":"mdi:android"} }],
  ["/wiki/Artificial%20Intelligence.html", { loader: () => import(/* webpackChunkName: "wiki_Artificial Intelligence.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Artificial Intelligence.html.js"), meta: {"title":"Artificial Intelligence","icon":"mdi:robot"} }],
  ["/wiki/Audio.html", { loader: () => import(/* webpackChunkName: "wiki_Audio.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Audio.html.js"), meta: {"title":"Audio","icon":"mdi:headphones"} }],
  ["/wiki/Books.html", { loader: () => import(/* webpackChunkName: "wiki_Books.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Books.html.js"), meta: {"title":"Books","icon":"mdi:book-open-page-variant"} }],
  ["/wiki/Documents.html", { loader: () => import(/* webpackChunkName: "wiki_Documents.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Documents.html.js"), meta: {"title":"Documents","icon":"mdi:file-document-outline"} }],
  ["/wiki/Downloading.html", { loader: () => import(/* webpackChunkName: "wiki_Downloading.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Downloading.html.js"), meta: {"title":"Downloading","icon":"mdi:download-circle-outline"} }],
  ["/wiki/Educational.html", { loader: () => import(/* webpackChunkName: "wiki_Educational.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Educational.html.js"), meta: {"title":"Educational","icon":"mdi:school-outline"} }],
  ["/wiki/Files.html", { loader: () => import(/* webpackChunkName: "wiki_Files.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Files.html.js"), meta: {"title":"Files","icon":"mdi:folder-multiple-outline"} }],
  ["/wiki/Images.html", { loader: () => import(/* webpackChunkName: "wiki_Images.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Images.html.js"), meta: {"title":"Images","icon":"mdi:image-multiple-outline"} }],
  ["/wiki/iOS.html", { loader: () => import(/* webpackChunkName: "wiki_iOS.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/iOS.html.js"), meta: {"title":"iOS","icon":"mdi:apple-ios"} }],
  ["/wiki/MacOS.html", { loader: () => import(/* webpackChunkName: "wiki_MacOS.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/MacOS.html.js"), meta: {"title":"MacOS","icon":"mdi:apple"} }],
  ["/wiki/Miscellaneous.html", { loader: () => import(/* webpackChunkName: "wiki_Miscellaneous.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Miscellaneous.html.js"), meta: {"title":"Miscellaneous","icon":"mdi:dots-horizontal-circle-outline"} }],
  ["/wiki/Privacy.html", { loader: () => import(/* webpackChunkName: "wiki_Privacy.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Privacy.html.js"), meta: {"title":"Privacy","icon":"mdi:shield-lock-outline"} }],
  ["/wiki/", { loader: () => import(/* webpackChunkName: "wiki_index.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/index.html.js"), meta: {"title":"Welcome to Kalyankari Collection","icon":"fa6-solid:hand-sparkles"} }],
  ["/wiki/Security.html", { loader: () => import(/* webpackChunkName: "wiki_Security.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Security.html.js"), meta: {"title":"Security","icon":"mdi:security"} }],
  ["/wiki/Self-Improvement.html", { loader: () => import(/* webpackChunkName: "wiki_Self-Improvement.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Self-Improvement.html.js"), meta: {"title":"Self-Improvement","icon":"mdi:brain"} }],
  ["/wiki/Social%20Media.html", { loader: () => import(/* webpackChunkName: "wiki_Social Media.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Social Media.html.js"), meta: {"title":"Social Media","icon":"mdi:account-group-outline"} }],
  ["/wiki/Text.html", { loader: () => import(/* webpackChunkName: "wiki_Text.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Text.html.js"), meta: {"title":"Text","icon":"mdi:text-box-outline"} }],
  ["/wiki/Videos.html", { loader: () => import(/* webpackChunkName: "wiki_Videos.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Videos.html.js"), meta: {"title":"Videos","icon":"mdi:video-outline"} }],
  ["/wiki/Web.html", { loader: () => import(/* webpackChunkName: "wiki_Web.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Web.html.js"), meta: {"title":"Web","icon":"mdi:web"} }],
  ["/wiki/Windows.html", { loader: () => import(/* webpackChunkName: "wiki_Windows.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/wiki/Windows.html.js"), meta: {"title":"Windows","icon":"mdi:microsoft-windows"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/kalyankari-collection/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
]);
